### ISSUE TITLE
Double description on "promise"?

### ISSUE THREAD

**Issue by kud** [tomv564/lsp-tsserver#12]
<img width="519" alt="image" src="https://user-images.githubusercontent.com/655838/63253685-9ac25c80-c272-11e9-8947-0491b7704ac5.png">

**Comment by tomv564** [comment]
lsp-tsserver only converts the `documentation` field from the QuickInfo structure returned from the typescript api using another typescript api: 
```
    const documentation = ts.displayPartsToString(info.documentation);
    if (documentation) {
        contents.push(documentation);
    }
```
I wonder if some parts of said `documentation` are duplicated and expected to be filtered?

**Comment by kud** [comment]
in `/usr/local/lib/node_modules/typescript/lib/lib.es5.d.ts`

```
/**
 * Represents the completion of an asynchronous operation
 */
interface Promise<T> {
    /**
     * Attaches callbacks for the resolution and/or rejection of the Promise.
     * @param onfulfilled The callback to execute when the Promise is resolved.
     * @param onrejected The callback to execute when the Promise is rejected.
     * @returns A Promise for the completion of which ever callback is executed.
     */
    then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): Promise<TResult1 | TResult2>;

    /**
     * Attaches a callback for only the rejection of the Promise.
     * @param onrejected The callback to execute when the Promise is rejected.
     * @returns A Promise for the completion of the callback.
     */
    catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): Promise<T | TResult>;
}
```

**Comment by kud** [comment]
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/655838/63267833-28ae3f80-c293-11e9-966c-97d7c60c2874.png">

**Comment by kud** [comment]
Is it the reason?

**Comment by tomv564** [comment]
It could be a typescript bug (can see if it occurs in their issues) or a result of specifying extra 'lib'  entries in your tsconfig.json?

**Comment by kud** [comment]
I don't have any `tsconfig.json` to be frank. I only use TypeScript Server for ES6 JavaScript code, and it happens only with Promise.

<img width="1015" alt="image" src="https://user-images.githubusercontent.com/655838/63268241-049f2e00-c294-11e9-8a69-c3d471167c8a.png">


And to be frank (again), I now use `typescript-language-server` which has the same troubles.

<img width="531" alt="image" src="https://user-images.githubusercontent.com/655838/63268324-3a441700-c294-11e9-990e-f6f231170e08.png">


I have to check more deeply but it ain't the fault of this app, thanks and sorrry!
