### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by Narretz** [tomv564/lsp-tsserver#13]
Hi,
can you please cut a new release?
I installed the current npm version from last year, and there are some problems (basically doc state isn't updating after you make changes) that are solved in master. So it would be really cool to have an official release, since this server is much faster then theia and sourcegraph.

**Comment by tomv564** [comment]
Thanks for opening the issue and reminding me - I'll make some time for it now that I know people are using it! :)

**Comment by tomv564** [comment]
Sorry this took a while, but 0.0.5 is out today!
