### ISSUE TITLE
Doesn't show type in autocomplete dropdown for local function, const, var, let, module

### ISSUE THREAD

**Issue by Narretz** [tomv564/lsp-tsserver#14]
I noticed that the server doesn't return the types for local function, const, var, let, module (and possibly others), in contrast to methods and properties. I've attached two screenshots as examples.
![tsserver-const](https://user-images.githubusercontent.com/1153097/70184645-89e60b80-16e8-11ea-89c3-b3a045566ec6.png)
![tsserver-module](https://user-images.githubusercontent.com/1153097/70184646-89e60b80-16e8-11ea-8f03-a08080b43714.png)

I did some digging and found this block in protocol.ts https://github.com/tomv564/lsp-tsserver/blob/373f3707f386a896554007d695cf133ba7c12840/src/protocol.ts#L34-L44 where some symbol types are commented out. If you can give me some pointer where to fix this, I can take a shot at it.

**Comment by tomv564** [comment]
You were close, I added some of the missing entries just above those lines. Are you running from master or from NPM? (it may take some time before I publish a release again).

**Comment by Narretz** [comment]
Thanks @tomv564 - I'm running on master, so no rush with the release
