### ISSUE TITLE
0x0d (\r) added when adding imports

### ISSUE THREAD

**Issue by princemaple** [tomv564/lsp-tsserver#3]
I'm on windows, but all my code files are using linux style newlines.
Is there a way to make it not add 0x0d?

**Comment by tomv564** [comment]
Hi @princemaple,

You can try adding a `formatOptions` to your editor's lsp-tsserver configuration. 
If you are using Sublime with LSP, it would go under `settings` like this:
```
    "settings": {
        "formatOptions": {
            "newLineCharacter": "\n"
        }
    }
```

**Comment by princemaple** [comment]
Indeed I'm on Sublime. I'll try that and report back. Thanks a lot!

**Comment by princemaple** [comment]
Thank you! Seems to work fine now.
