### ISSUE TITLE
not working for Typescript

### ISSUE THREAD

**Issue by AmjadHD** [tomv564/lsp-tsserver#4]
These are my configs:
```
{
    "js": {
        "command": ["lsp-tsserver"],
        "enabled": true,
        "languageId": "javascript",
        "scopes": ["source.js"],
        "syntaxes": ["Packages/JavaScript/JavaScript.sublime-syntax"]
    },
    "jsts": {
        "command": ["lsp-tsserver"],
        "enabled": true,
        "languageId": "typescript"
        "scopes": ["source.ts", "source.tsx"],
        "syntaxes": ["Packages/TypeScript-TmLanguage/TypeScript.tmLanguage", "Packages/TypeScript-TmLanguage/TypeScriptReact.tmLanguage"],
    }
}
```
it works for javascript files but not for typescript.
for typescript it does start but then nothing happens, all LSP does is send `"textDocument/didSave"` when the file is saved.
another thing is the `language` for javascript files is `typescript`:
```
LSP:  --> textDocument/hover
LSP:      {'contents': [{'language': 'typescript', 'value': 'test(argument: any): void'}, '**local function**']}
```
shouldn't it be `javascript` ?

**Comment by tomv564** [comment]
This missing document sync looks like a problem with the Sublime package, not this server?

The `typescript` is hardcoded - there is no easy way to determine what language is being presented from the "QuickInfo" received from the API used for Hover.

**Comment by AmjadHD** [comment]
sublime text provides API to find the "language" like score_selector ,match selector or view.settings().get("syntax"), I didn't get what you mean by "hardcoded" ?

**Comment by tomv564** [comment]
The `typescript` is always returned by this server even in javascript documents - it's not a symptom of your problem (it can be fixed, but doesn't really hurt either).

Can you open an issue in the LSP repo, and try some of the steps from the troubleshooting page (https://lsp.readthedocs.io/en/latest/#troubleshooting)?
