### ISSUE TITLE
Error for textDocument/hover and others starting at version 0.0.1

### ISSUE THREAD

**Issue by rzec-r7** [tomv564/lsp-tsserver#5]
This was originally posted in the main LSP repo but posting here based on feedback.

One additional piece of information I can provide is that the issue below shows up for version all version back including `0.0.1`.

**Original Issue:**
---

OS: Max OS X
LSP Source: Package Manager

My config:

```json
{
  "clients": {
     "js": {
      "command": ["lsp-tsserver"],
      "enabled": true,
      "languageId": "javascript",
      "scopes": ["source.js"],
      "syntaxes": ["Packages/Babel/JavaScript (Babel).sublime-syntax", "Packages/JavaScript/JavaScript.sublime-syntax"]
    }
  },
  "log_debug": true,
  "log_server": true,
  "log_stderr": true,
  "log_payloads": true
}
```

I have an npm package that does something like this:
```js
//...
import * as utils from 'src/utils';
//...
```

and then exports that like this:

```js
export {
  //...
  utils,
  //...
}; 
```

Then I import that like this:

```js
import {utils} from 'npm-package-name';
```

now if I do `utils.` I get a list of the expected auto complete results however when I select a function for example, I get this error:

```
LSP:  --> textDocument/signatureHelp
LSP:      {'code': -32603, 'message': 'Request textDocument/signatureHelp failed with message: Debug Failure. False expression.'}
```

if I hover over the function name, I get pretty much the same thing:

```
LSP:  --> textDocument/hover
LSP:      {'code': -32603, 'message': 'Request textDocument/hover failed with message: Debug Failure. False expression.'}
```

The same exact code give the function signature help in VS Code so I am not sure what is going on here.

**Comment by tomv564** [comment]
I updated to typescript 3.0.1, could you try installing lsp-tsserver 0.0.4? (there was one example of this failure fixed in that release).

That said, it would be nice to have the full error and stack trace, and I wonder if that would be visible if you had LSP's `log_stderr` setting on, and run the server with 
```
"lsp-tsserver", "--traceToConsole", "true", "--logVerbosity", "terse"
```

**Comment by rzec-r7** [comment]
@tomv564 I don't see 0.0.4 on npm for `lsp-tsserver`

**Comment by tomv564** [comment]
Sorry, now it’s published
